base_dir: "/mnt/d/BRLAB/2025/mizuno/done/kaiseki1"

batch_warp:
  dict: "4X4_50"
  marker_size_cm: 14.5
  px_per_m: 400
  alpha: 0.3
  scan_step: 1
  scan_max: 2000
  candidates_top: 30
  reproj_thresh_px: 2.0
  superres: 1.25
  debug_dir: "{base}/syaeihenkann/ninsiki"
  save_csv: true
  save_best_k: 5
  fisheye: false
  calib_size: "1920x1080"
  crop_roi: false
  expected_id: 0
  workers: 0

  pairs:
    - name: cam1
      calib: "{base}/frame/cam1/cam1_1080p.yaml"
      video: "{base}/walk/cam1_walk.mp4"
      out:   "{base}/syaeihenkann/cam1_on_plane.mp4"
      select_detect_roi: true     # ← ここをtrueに
      select_roi_frame:  100      # ← ROI選択に使うフレーム（お好みで）

    - name: cam2
      calib: "{base}/frame/cam2/cam2_1080p.yaml"
      video: "{base}/walk/cam2_walk.mp4"
      out:   "{base}/syaeihenkann/cam2_on_plane.mp4"
      select_detect_roi: true
      select_roi_frame:  100
